[theme]
primaryColor = "#2eb67d"  # Verde para tema ambiental
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true
magicEnabled = true
installTracer = false
fixMatplotlib = true
